export const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED'
export const INCREMENT = 'counter/INCREMENT'
export const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED'
export const DECREMENT = 'counter/DECREMENT'
export const SET_ASYNC_PERIOD = 'counter/SET_ASYNC_PERIOD'

export const SEARCH_ADDRESS = 'geo/SEARCH_ADDRESS';
export const SEARCH_ADDRESS_SUCCESS = 'geo/SEARCH_ADDRESS_SUCCESS';
export const SEARCH_ADDRESS_FAIL = 'geo/SEARCH_ADDRESS_FAIL';

export const SELECT_RESULT = 'geo/SELECT_RESULT';